### ISSUE TITLE
이건 뭐가 문제일까요 ㅠㅠ

### ISSUE THREAD

**Issue by YJ-A** [istandthon7/torrent_web_scraper#2]
안녕하세요.
처음 사용해보는 유저입니다.
아래와 같은 에러가 나는데 뭐가 문제일까요 ㅠㅠ?

root@istandthon7-torrentscraper1:/torrent_web_scraper# ./torrent_web_scraper.py 
Exception getBsObj url: https://torrentsir31.com/, error: <urlopen error [Errno 
-3] Temporary failure in name resolution>

**Comment by YJ-A** [comment]
아 방화벽이 문제였네요;; 감사히 잘쓰겠습니다~~

**Comment by istandthon7** [comment]
처음 사용하시는 분들도 불편하지 않도록 에러메시지를 개선하도록 하겠습니다.
