### ISSUE TITLE
특정 타이틀 스크랩이 안됩니다

### ISSUE THREAD

**Issue by whatduckhell** [istandthon7/torrent_web_scraper#34]
2.2.02 에서는 키워드를  ".23" 설정하고
`태어난 김에 세계일주2.E02.230618.1080p.WANNA`
`미친(味親) 원정대.E02.230620.1080p.H264-F1RST`
이런 타이틀이 스크랩이 되는데
이후 버전에서는 공백오류 수정후에도 스크랩이 안되네요

그리고 저는 tvshow 폴더생성을 안하려고 
`__main__.py`
`downloadPath += tvshowDownloadPath + "/" + regKeyword`
`downloadPath += tvshowDownloadPath`
이렇게 쓰고 있는데 옵션으로 설정 기능추가가 가능한지요

개발자님의 세심한 배려덕분에 잘 사용하고 있습니다 감사합니다

**Comment by istandthon7** [comment]
안녕하세요. 상세한 리포트 감사드려요.
설정파일에서 로그를 INFO로 변경했을 때 
`INFO:게시물 아이디를 확인할 수 없습니다.`
이 로그가 남는지 확인 부탁드립니다.

**Comment by whatduckhell** [comment]
말씀하신 게이물 아이디를 확인할수 없습니다라는 오류는 없구요.

```
 "tvshow": {
    "checkEpisodeNubmer": "false",
```
설정이 추가 되어있는데
`세컨 하우스2.E04.230622.1080p.H264-F1RST`
`세컨 하우스2.E04.230622.720p.H264-F1RST`

```
		,{"name": ".23", "option": "720","option2":"F1RST", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"F1RST", "exclude":"완결, ts" }
```
두가지 모두 다 받는 경우에 스크랩이 안됩니다.
`INFO:이미 다운로드 받은 회차입니다. .23, 세컨 하우스2.E04.230622.720p.H264-F1RST`

```
2023-06-23 15:00:26,030 INFO:게시물을 검색하였습니다. 빵카로드 2.E08.230621.1080p.H264-F1RST
2023-06-23 15:00:30,048 INFO:이미 다운로드 받은 회차입니다. .23, 빵카로드 2.E08.230621.1080p.H264-F1RST
```
그리고 빵카로드 2는 다른 해상도도 겹치는게 없고 다운로드 받은게 없는데도 이미 받았다고 나오네요
히스토리csv 삭제하고 셋팅에서 히스토리와 넘버를 0으로 초기화한뒤에 시도해봤습니다

` "checkEpisodeNubmer": "true",`
설정도 해봤는데 동일한 결과 같아요

**Comment by istandthon7** [comment]
확인해 주셔서 감사합니다. 
신규로 설치해서 확인해 보니 동일 증상이 나오진 않아 원인파악에 어려움이 있네요.
가능하다면 config폴더 압축해서 보내주시면 동일 설정에서 테스트해 보도록 하겠습니다.

**Comment by whatduckhell** [comment]
setting.json
`{
  "logging": {
    "logFile": "scraper.log",
    "logLevel": "INFO"
  },
  "movie": {
    "download": "",
    "exclude": "",
    "list": "Movie.txt",
    "resolution": 1080,
    "titleScrap": {
      "ranking": 8,
      "url": "https://movie.daum.net/ranking/boxoffice/monthly"
    },
    "videoCodec": "264"
  },
  "notification": {
    "cmd": "",
    "history": "notiHistory.csv",
    "keywords": [
      "키워드",
      "키워드2"
    ]
  },
  "sites": [
    {
      "categories": [
        {
          "history": 319702,
          "name": "예능·오락",
          "number": 42125,
          "scrapPage": 3,
          "title": {
            "class": "tit",
            "tag": "li"
          },
          "url": "topic/index?category1=4&category2=16"
        }
      ],
      "enable": true,
      "mainUrl": "https://torrentsee170.com/",
      "name": "토렌트씨"
    }
  ],
  "torrentFail": "torrentFail.csv",
  "torrentHistory": "torrentHistory.csv",
  "transmission": {
    "host": "127.0.0.1",
    "id": "",
    "pgid": 1000,
    "port": 9091,
    "puid": 1000,
    "pw": ""
  },
  "tvshow": {
    "checkEpisodeNubmer": "false",
    "download": "/data/fun",
    "list": "TVShow.json"
  }
}`

TVShow.json
`{
    "json parser": "http://json.parser.online.fr/",
    "title_list": [
		{"name": ".23", "option": "720","option2":"NEXT", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"NEXT", "exclude":"완결, ts" }
		,{"name": ".23", "option": "720","option2":"F1RST", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"F1RST", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"Sniper", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"CJH", "exclude":"완결, ts" }
		,{"name": ".23", "option": "1080","option2":"WANNA", "exclude":"완결, ts" }
    ]
}
`
위에꺼는 제가 쓰는 see config 입니다

git 최신버전으로 땡겨서 main.py 수정없이 
다운경로 트랜스미션설정 "checkEpisodeNubmer": "false", 설정하고
디폴트값인 qq 로도 해봤는데요 
동일하게 중복된다고 스크랩이 안되고있습니다
```
2023-06-23 22:25:49,048 INFO:게시물을 검색하였습니다. N세컨 하우스2.E04.230622.1080p.H264-F1RST.
2023-06-23 22:25:51,537 INFO:Transmission에 추가하였습니다. .23, magnet:?xt=urn:btih:a1029b68db38c133d3c613a463a94731f7f75d86, 폴더: [/data/*****/test/.23]
2023-06-23 22:25:51,542 INFO:[.23] option2가 달라요. [NEXT]
2023-06-23 22:25:51,542 INFO:[.23] option이 달라요. [1080]
2023-06-23 22:25:51,542 INFO:게시물을 검색하였습니다. N세컨 하우스2.E04.230622.720p.H264-F1RST
2023-06-23 22:25:53,007 INFO:이미 다운로드 받은 회차입니다. .23, N세컨 하우스2.E04.230622.720p.H264-F1RST 
```

제 TVShow.json 설정이 문제일까요? 근데 2.2.02 까지는 문제가 없습니다.

**Comment by istandthon7** [comment]
"checkEpisodeNubmer": "false", --> "checkEpisodeNubmer": false,
변경하면 될 것 같습니다.
