### ISSUE TITLE
작동이 되질 않아 문의드립니다.

### ISSUE THREAD

**Issue by sH1222J** [istandthon7/torrent_web_scraper#6]
순서가 맞는지 확인 부탁드립니다.

패키지 센터 도커 설치
도커 실행 후 이미지 URL에 istandthon7 / torrentscraper 추가하여 다운로드 후 실행
고급 설정-볼륨 설정-/ docker / scraper_config / / torrent_web_scraper / config 적용
docker \ scraper_config \ setting.json 텍스트 에디터 이용해 편집-
"trans-host": "자신의시 놀로지 내부 주소",
"trans-id": "아뒤",
"trans-port": "9091",
"trans- pw ":"비번 "
.docker \ scraper_config \ TVShow.json 텍스트 에디터 이용해 편집 이용해 원하는 제목 설정
시 놀로지 작업 스케줄러 접속 후 작성 생성 docker exec -t istandthon7-torrentscraper1 ./torrent_web_scraper.py
http : // 해당 NAS 내부 아이피 : 9091 / 트랜스미션 웹 접속 확인
작동 하질 작동 하질. 틀린 부분 존재 부탁드립니다.

참고로 방화벽 비활성화 및 도커 컨테이너에서 해당 이미지 다시 시작, torrent_web_scraper 터미널에서 ./torrent_web_scraper
.py 급한 입력하여 실행하여 해결되지 않았습니다.

**Comment by istandthon7** [comment]
개인적인 프로젝트라 이슈를 모니터링하지 못해 답변이 늦었습니다. 
동영상 링크입니다. 확인 후 궁금하신 사항 남겨주세요. 감사합니다.

https://cloud.wnote.kr/index.php/s/FrQifJWbMeXL3pH
